### ISSUE TITLE
Implement `/authorize` and `/token` endpoints

### ISSUE THREAD

**Issue by michaljanocko** [havenworks/patrol#1]
Need to implement `/oauth/authorize` and `/oauth/token` endpoints that are OAuth 2.0 compliant and behave predictably.

Great resources are:

- [oauth.com](https://oauth.com)
- [RFC 6749](https://www.rfc-editor.org/rfc/rfc6749)

**Comment by rosenbergm** [comment]
I worked on implementing the `/authorize` endpoint with PKCE support yesterday. Much progress has been made. I think it might be done today or tomorrow.
